# Generated by Django 6.0.6 on 2026-06-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treading_mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GapUpStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('trade_date', models.DateField(db_index=True)),
                ('prev_open', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prev_high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prev_low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prev_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('today_open', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('today_high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('today_low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('today_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('open_diff', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high_diff', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low_diff', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('close_diff', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gap_up', models.BooleanField(default=False)),
                ('gap_down', models.BooleanField(default=False)),
                ('gap_type', models.CharField(default='NO GAP', max_length=30)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('candle_start', models.TimeField(blank=True, null=True)),
                ('candle_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'unique_together': {('symbol', 'trade_date')},
            },
        ),
    ]
