# Generated by Django 6.0.6 on 2026-06-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treading_mainapp', '0002_gapupstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gapupstatus',
            old_name='updated_at',
            new_name='refreshed_at',
        ),
        migrations.AddField(
            model_name='gapupstatus',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='gapupstatus',
            name='data_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gapupstatus',
            name='prev_trade_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gapupstatus',
            name='gap_type',
            field=models.CharField(choices=[('GAP UP', 'GAP UP'), ('GAP DOWN', 'GAP DOWN'), ('NO GAP', 'NO GAP')], default='NO GAP', max_length=20),
        ),
        migrations.AlterField(
            model_name='gapupstatus',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gapupstatus',
            name='symbol',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
