# Generated by Django 6.0.6 on 2026-06-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treading_mainapp', '0003_rename_updated_at_gapupstatus_refreshed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gapupstatus',
            name='gap_type',
            field=models.CharField(choices=[('GAP UP', 'GAP UP'), ('GAP DOWN', 'GAP DOWN'), ('NO GAP', 'NO GAP'), ('SCAN FAILED', 'SCAN FAILED')], default='NO GAP', max_length=20),
        ),
    ]
