# Generated by Django 6.0.6 on 2026-07-01 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treading_mainapp', '0005_whatsappcampaign_whatsappcontact_whatsappmessagelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GapScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True)),
                ('scan_type', models.CharField(choices=[('AUTO_0930', 'Auto 09:30'), ('MANUAL', 'Manual'), ('FORCE', 'Force'), ('FINAL', 'Final')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('trigger_source', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('lock_token', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-trade_date', '-started_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterUniqueTogether(
            name='gapupstatus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappcontact',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gapupstatus',
            name='gap_type',
            field=models.CharField(choices=[('GAP UP', 'GAP UP'), ('GAP DOWN', 'GAP DOWN'), ('NO GAP', 'NO GAP'), ('SCAN FAILED', 'SCAN FAILED')], db_index=True, default='NO GAP', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='gapupstatus',
            index=models.Index(fields=['trade_date', 'symbol'], name='idx_gap_trade_symbol'),
        ),
        migrations.AddIndex(
            model_name='gapupstatus',
            index=models.Index(fields=['trade_date', 'gap_type'], name='idx_gap_trade_type'),
        ),
        migrations.AddIndex(
            model_name='gapupstatus',
            index=models.Index(fields=['trade_date', 'gap_up'], name='idx_gap_trade_gapup'),
        ),
        migrations.AddIndex(
            model_name='gapupstatus',
            index=models.Index(fields=['trade_date', 'gap_down'], name='idx_gap_trade_gapdown'),
        ),
        migrations.AddIndex(
            model_name='whatsappcampaign',
            index=models.Index(fields=['owner', 'status'], name='idx_wa_campaign_owner_status'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['owner', 'is_active'], name='idx_wa_contact_owner_active'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['campaign', 'status'], name='idx_wa_log_campaign_status'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['contact', 'status'], name='idx_wa_log_contact_status'),
        ),
        migrations.AddConstraint(
            model_name='gapupstatus',
            constraint=models.UniqueConstraint(fields=('symbol', 'trade_date'), name='uniq_gap_status_symbol_trade_date'),
        ),
        migrations.AddConstraint(
            model_name='whatsappcontact',
            constraint=models.UniqueConstraint(fields=('owner', 'phone'), name='uniq_wa_contact_owner_phone'),
        ),
        migrations.AddIndex(
            model_name='gapscanrun',
            index=models.Index(fields=['trade_date', 'status'], name='idx_scanrun_trade_status'),
        ),
        migrations.AddIndex(
            model_name='gapscanrun',
            index=models.Index(fields=['trade_date', 'scan_type'], name='idx_scanrun_trade_type'),
        ),
    ]
