# Generated by Django 5.2.5 on 2026-07-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treading_mainapp', '0007_fix_userprofile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='whatsappcontact',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='contact',
        ),
        migrations.DeleteModel(
            name='WhatsAppCampaign',
        ),
        migrations.DeleteModel(
            name='WhatsAppContact',
        ),
        migrations.DeleteModel(
            name='WhatsAppMessageLog',
        ),
    ]
